version: '3.8'

services:
  composer:
    build:
      context: ./composer
      dockerfile: Dockerfile
    image: groupe7/composer-custom:1.0.1
    volumes:
      - ./app:/var/www/symfony 
    working_dir: /var/www/symfony
    command: install
    

  symfony:
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    build:
      context: ./symfony
      dockerfile: Dockerfile
    image: groupe7/symfony-custom:1.0.1
    volumes:
      - ./app:/var/www/symfony  
    networks:
      - net-for-symfony
      - net-for-db
    depends_on:
      - composer

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  
    volumes:
      - ./nginx/nginx.conf/default.conf:/etc/nginx/conf.d/default.conf  
      - ./app:/var/www/symfony 
    depends_on:
      - symfony  
    networks:
      - net-for-symfony  

networks:
  net-for-symfony:
    name: symphony-app 
  net-for-db:
    external: true
    name: back-db  
